FUNCTION(DEDUCE_LIBPNG_PATH)
	execute_process(
		COMMAND brew --prefix libpng
		OUTPUT_VARIABLE LIBPNG_PATH
		OUTPUT_STRIP_TRAILING_WHITESPACE)

	set(LIBPNG_PATH ${LIBPNG_PATH} PARENT_SCOPE)
ENDFUNCTION()