FUNCTION(DEDUCE_LIBPNG_PATH)
	execute_process(
		COMMAND brew list --versions libpng
		OUTPUT_VARIABLE LIBPNG_WITH_VERSION
		OUTPUT_STRIP_TRAILING_WHITESPACE)

	set(regex_pattern "([0-9]+\\.[0-9]+\\.[0-9]+)")
	string(REGEX MATCH "${regex_pattern}" LIBPNG_VERSION "${LIBPNG_WITH_VERSION}")

	execute_process(
		COMMAND brew --cellar libpng
		OUTPUT_VARIABLE LIBPNG_HOMEBREW_PATH
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)

	set(LIBPNG_PATH "${LIBPNG_HOMEBREW_PATH}/${LIBPNG_VERSION}" PARENT_SCOPE)
ENDFUNCTION()