//damage types
#define DAMAGE_CRUSHING 0
#define DAMAGE_ACID     1
#define DAMAGE_COLD     2
#define DAMAGE_ELECTRICITY 4
#define DAMAGE_FIRE     8
#define DAMAGE_PIERCING 0x10
#define DAMAGE_POISON 0x20
#define DAMAGE_MAGIC 0x40
#define DAMAGE_MISSILE 0x40
#define DAMAGE_SLASHING 0x100
#define DAMAGE_MAGICFIRE 0x200
#define DAMAGE_PIERCINGMISSILE 0x400 //iwd2
#define DAMAGE_MAGICCOLD 0x400
#define DAMAGE_CRUSHINGMISSILE 0x400 //iwd2
#define DAMAGE_STUNNING 0x800
#define DAMAGE_SOULEATER 0x1000  //iwd2
#define DAMAGE_DISEASE 0x4000    //iwd2

#define DAMAGE_CHUNKING 0x8000
//damage levels
#define DL_BLOOD  0
#define DL_CRITICAL 3
#define DL_FIRE   4
#define DL_ELECTRICITY  7
#define DL_COLD   11
#define DL_ACID   14
#define DL_DISINTEGRATE 17

