
IE_SEX =		35
global IE_SEX
IE_KIT =	152 
global IE_KIT
IE_RACE =		201
global IE_CLASS
IE_MINOR_COLOR =	209
global IE_MINOR_COLOR
IE_MAJOR_COLOR =	210
global IE_MAJOR_COLOR
IE_SKIN_COLOR =		211
global IE_SKIN_COLOR
IE_HAIR_COLOR =		214
global IE_HAIR_COLOR
IE_ALIGNMENT =		217
global IE_ALIGNMENT
