name: Style checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50

    - name: Setup Python
      uses: actions/setup-python@v1
  
    - name: python-lint whitespace check
      run: |
        git fetch origin
        pip install pycodestyle &&
        git diff -u origin/${{github.base_ref}}... -- gemrb/GUIScripts | pycodestyle --select=E1,E201,E202,E203,E225 --diff --show-source

    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
        tidy-checks: '-*'
        version: 17
        lines-changed-only: true
        ignore: "gemrb/include/fmt|platforms"
        step-summary: true

    - name: Fail if there is not conformance with clang-format
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
